<a href="https://colab.research.google.com/github/saeidakbari3364/Python-Tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Tutorial

In [1]:
import numpy as np

In [2]:
from time import process_time

In [4]:
python_list=[i for i in range(1000)]

Time Taken by List

In [8]:
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()

In [11]:
print(end_time-start_time)

0.0002875390000003364


In [14]:
np_array=np.array([i for i in range(100)])
start_time=process_time()
np_array+=5
end_time=process_time()

In [15]:
print(end_time-start_time)

0.0015913409999992467


In [16]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [17]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [18]:
#Creating 1 dimention array
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [19]:
a.shape

(5,)

In [20]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [26]:
c=np.array([[1,2,3],[4,5,6]],dtype=float)
print(c)
type(c)


[[1. 2. 3.]
 [4. 5. 6.]]


numpy.ndarray

In [27]:
c.shape

(2, 3)

Initial Placeholder in Numpy arrays

In [28]:
# Create a numpy array of zero

In [30]:
 x=np.zeros((4,5))
 x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
#Creat a numpy array of ones

In [32]:
y=np.ones((4,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
#create a numpy array by particular value

In [34]:
z=np.full((3,2),5)
z

array([[5, 5],
       [5, 5],
       [5, 5]])

In [35]:
#Create an identity matrix
w=np.eye(4)
w

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#create a numpy array with Random value

In [37]:
r=np.random.random((3,4))
r

array([[0.95406299, 0.14209945, 0.07490581, 0.34418328],
       [0.1688501 , 0.77212892, 0.91895612, 0.32385701],
       [0.79776769, 0.00586225, 0.18350637, 0.51246711]])

In [39]:
#Create a numpy array with Random integer values within a specific range

In [40]:
c=np.random.randint(10,100,(3,5))
c

array([[18, 64, 53, 55, 90],
       [13, 80, 22, 30, 33],
       [76, 10, 62, 68, 78]])

In [41]:
#array of evenly spaced value--->specifiying the number of values required

In [45]:
d=np.linspace(10,30,5)
d

array([10., 15., 20., 25., 30.])

In [46]:
#array of evenly spaced value--->specifiying the step

In [47]:
f=np.arange(10,30,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [48]:
#convert a list into a numpy array

In [49]:
list2=[1,2,3,4]
np_array=np.asarray(list2)
np_array

array([1, 2, 3, 4])

In [50]:
#Analysing a nump array

In [51]:
c=np.random.randint(10,90,(5,5))
c

array([[60, 26, 85, 37, 82],
       [21, 28, 85, 79, 75],
       [39, 57, 39, 86, 43],
       [54, 14, 29, 16, 85],
       [88, 26, 27, 42, 73]])

In [52]:
#array dimention
c.shape

(5, 5)

In [53]:
#number of dimention

In [54]:
c.ndim

2

In [55]:
#number of elements

In [56]:
c.size

25

In [57]:
 #checking the data type in the array

In [58]:
c.dtype

dtype('int64')

Mathematical Operations on a numpy array

In [60]:
list1=[1,2,3,4]
list2=[5,6,7,8]

print(list1+list2)#Concatenate or joins

[1, 2, 3, 4, 5, 6, 7, 8]


In [61]:
a=np.random.randint(0,10,(3,3))
a

array([[4, 1, 1],
       [9, 3, 8],
       [6, 5, 4]])

In [63]:
b=np.random.randint(10,20,(3,3))
b

array([[12, 11, 14],
       [17, 19, 19],
       [16, 17, 12]])

In [64]:
#element wise
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 12 15]
 [26 22 27]
 [22 22 16]]
[[ -8 -10 -13]
 [ -8 -16 -11]
 [-10 -12  -8]]
[[ 48  11  14]
 [153  57 152]
 [ 96  85  48]]
[[0.33333333 0.09090909 0.07142857]
 [0.52941176 0.15789474 0.42105263]
 [0.375      0.29411765 0.33333333]]


In [65]:
np.add(a,b)

array([[16, 12, 15],
       [26, 22, 27],
       [22, 22, 16]])

In [66]:
np.subtract(a,b)

array([[ -8, -10, -13],
       [ -8, -16, -11],
       [-10, -12,  -8]])

In [67]:
np.multiply(a,b)

array([[ 48,  11,  14],
       [153,  57, 152],
       [ 96,  85,  48]])

In [68]:
np.divide(a,b)

array([[0.33333333, 0.09090909, 0.07142857],
       [0.52941176, 0.15789474, 0.42105263],
       [0.375     , 0.29411765, 0.33333333]])

Array Manipulation

In [69]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 0 4]
 [8 1 3]]
(2, 3)


In [70]:
#transpose of a matrix

In [72]:
trans=np.transpose(a)
trans

array([[4, 8],
       [0, 1],
       [4, 3]])

In [73]:
trans.shape

(3, 2)

In [74]:
#another way of transpose

In [75]:
trans2=a.T

In [76]:
trans2

array([[4, 8],
       [0, 1],
       [4, 3]])

In [77]:
#Reshape of an array

In [78]:
a=np.random.randint(0,10,(2,3))
a

array([[8, 6, 5],
       [6, 6, 5]])

In [79]:
a.shape

(2, 3)

In [80]:
b=a.reshape(3,2)

In [81]:
b

array([[8, 6],
       [5, 6],
       [6, 5]])

In [83]:
b.shape

(3, 2)